[package]
name = "orm_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = "1"
quote = "1.0"
proc-macro2 = "1.0"
tokio = { version = "1", features = ["full"] }
scylla = "0.14.0"
anyhow = "1.0"

[lib]
proc-macro = true